store/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

urlpatterns = [
    path('', RedirectView.as_view(url='category/'), name='go-to-django'),
    path('category/', views.ListCategory.as_view(), name="list-category"),
    path('category/add/', views.CreateCategory.as_view(), name="create-category"),
    path('category/<int:pk>/', views.CategoryDetails.as_view(), name="category-details"),
    path('product/', views.ListProducts.as_view(), name="list-products"),
    path('product/<int:pk>/', views.ProductsDetails.as_view(), name="products-details"),
    path('product/add/', views.CreateProduct.as_view(), name="create-product"),
    path('supply/', views.ListDelivery.as_view(), name="list-delivery"),
    path('supply/<int:pk>/', views.SupplyDetails.as_view(), name="supply-details"),
    path('supply/add/', views.SupplyCreate.as_view(), name="create-supply"),
    path('supply/<int:supply_id>/add/', views.delivery_memory_create, name="create-delmem"),
    path('descent/', views.ListDescent.as_view(), name="list-descent"),
    path('descent/<int:pk>/', views.DescentDetails.as_view(), name="descent-details"),
    path('descent/add/', views.DescentCreate.as_view(), name="create-descent"),
    path('descent/<int:descent_id>/add/', views.descent_memory_create, name="create-desmem"),
    path('search/', views.search, name="search"),
]

werehouse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls)),
    ] + urlpatterns

store/models.py
from django.urls import reverse
from django.db import models
from django.utils import timezone

class Product(models.Model):
    name = models.CharField(
        max_length=200,
        verbose_name="NAZWA",
        help_text="Pełna nazwa produktu"
         )
    quantity = models.IntegerField(
        verbose_name="ILOŚĆ",
    )
    price = models.FloatField(
        verbose_name="CENA",

    )
    kind = models.CharField(
        verbose_name="TYP",
        max_length=200,
        help_text="Typ produktu"
    )
    category = models.ForeignKey(
        'Category',
        on_delete=models.PROTECT,
        verbose_name="KATEGORIA",
    )

    class Meta:
         ordering = ['name','quantity','price','kind']
    
    def get_absolute_url(self):
      return reverse('products-details', args=[self.pk])

    def __str__(self):
        return f"Produkt {self.name} z rodzaju {self.kind} w cenie {self.price} dostępny w ilości {self.quantity}"

class Category(models.Model):
    name = models.CharField(
        max_length=200,
        unique=True,
        verbose_name="Nazwa",
        help_text="Nazwa kategori"
    )

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ['name']

    def get_absolute_url(self):
      return reverse('list-category')
    
    def __str__(self):
        return self.name

class Supply(models.Model):
    supply_date=models.DateTimeField(
        default=timezone.now,
        verbose_name="DATA DOSTAWY",
        )
    products = models.ManyToManyField(
        Product,
        through='Delivery_memory',
    )
    

    class Meta:
         ordering = ['supply_date']

    def get_absolute_url(self):
      return reverse('supply-details', args=[self.pk])

    def __str__(self):
        return f"Dostawa z dnia : {self.supply_date}"




class Delivery_memory(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    supply =  models.ForeignKey(Supply, on_delete = models.CASCADE)
    quantity = models.IntegerField()

class Descent(models.Model):
    descent_date = models.DateTimeField(
        default=timezone.now,
        verbose_name="DATA ZEJŚCIA",
        )
    products = models.ManyToManyField(
        Product,
        through='Descent_memory',
    )
    

    class Meta:
         ordering = ['descent_date']
    
    def get_absolute_url(self):
      return reverse('descent-details', args=[self.pk])

    def __str__(self):
        return f"Produkt  wydany : {self.descent_date}"

class Descent_memory(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    descent =  models.ForeignKey(Descent, on_delete = models.CASCADE)
    quantity = models.IntegerField()

store/forms.py
from django import forms

from .models import Delivery_memory, Descent_memory


class DeliveryMemoryForm(forms.ModelForm):
    class Meta:
        model = Delivery_memory
        fields = ['product', 'quantity', 'supply']
        widgets = {'supply': forms.HiddenInput()}

class DescentMemoryForm(forms.ModelForm):
    class Meta:
        model = Descent_memory
        fields = ['product', 'quantity', 'descent']
        widgets = {'descent': forms.HiddenInput()}

store/views.py
from django.urls import reverse
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView

from .forms import DeliveryMemoryForm, DescentMemoryForm
from .models import Product, Category, Supply, Descent, Delivery_memory, Descent_memory
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


class ListCategory(ListView):
    model = Category
    template_name = 'store/category.html'
    extra_context = {
        'title': "Lista Kategori",
    }
    context_object_name = 'category_list'

class CategoryDetails(DetailView):
    model = Category
    template_name = 'store/category_details.html'
    context_object_name = 'category'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = self.object.name
        return context

class CreateCategory(LoginRequiredMixin, CreateView):
  model = Category
  fields = ['name']
  template_name = 'store/create_category.html'
  extra_context = {
    'title': "Dodaj nową kategorię:"
  }



class ListProducts(ListView):
    model = Product
    template_name = 'store/products.html'
    extra_context = {
        'title': "Lista Produktów",
    }
    context_object_name = 'products_list'


class ProductsDetails(DetailView):
    model = Product
    template_name = 'store/products_details.html'
    context_object_name = 'product'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = self.object.name
        return context

class CreateProduct(LoginRequiredMixin, CreateView):
  model = Product
  fields = ['name', 'price', 'kind', 'quantity', 'category']
  template_name = 'store/create_product.html'
  extra_context = {
    'title': "Dodaj nowy produkt:"
  }

class ListDelivery(ListView):
    model = Supply
    template_name = 'store/delivery.html'
    extra_context = {
        'title': "Lista dostaw",
    }
    context_object_name = 'delivery_list'

class SupplyDetails(DetailView):
    model = Supply
    template_name = 'store/supply.html'
    context_object_name = 'supply'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = self.object.supply_date
        return context

class SupplyCreate(CreateView):
    model = Supply
    fields = ['supply_date']
    template_name = 'store/supply_add.html'
    extra_context = {
        'title': "Dodaj dostawę"
    }
    def get_success_url(self):
        return reverse('create-delmem', args=[self.object.pk])
@login_required

def delivery_memory_create(request, supply_id):
    # 1 pobrac supply
    supply = get_object_or_404(Supply, pk=supply_id)

    # formularz
    if request.method == "POST":
        form = DeliveryMemoryForm(request.POST)
        
        if form.is_valid():
            obj = form.save()
            obj.product.quantity += obj.quantity
            obj.product.save()
            return redirect(supply.get_absolute_url())
    
    else:
        form = DeliveryMemoryForm(initial={'supply': supply.pk})
    
    context = {
        'title': 'Dodawanie szczegóły dostawy',
        'form': form,
    }

    return render(request, 'store/create_delivery.html', context)

class ListDescent(ListView):
    model = Descent
    template_name = 'store/descent_list.html'
    extra_context = {
        'title': "Lista zejść towaru",
    }
    context_object_name = 'descent_list'

class DescentDetails(DetailView):
    model = Descent
    template_name = 'store/descent.html'
    context_object_name = 'descent'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = self.object.descent_date
        return context


class DescentCreate(CreateView):
    model = Descent
    fields = ['descent_date']
    template_name = 'store/descent_add.html'
    extra_context = {
        'title': "Dodaj zejście"
    }
    def get_success_url(self):
        return reverse('create-desmem', args=[self.object.pk])

@login_required

def descent_memory_create(request, descent_id):
    # 1 pobrac supply
    descent = get_object_or_404(Descent, pk=descent_id)

    # formularz
    if request.method == "POST":
        form = DescentMemoryForm(request.POST)
        
        if form.is_valid():
            obj = form.save()
            obj.product.quantity -= obj.quantity
            obj.product.save()
            return redirect(descent.get_absolute_url())
    
    else:
        form = DescentMemoryForm(initial={'descent': descent.pk})
    
    context = {
        'title': 'Dodawanie szczegóły zejścia',
        'form': form,
    }

    return render(request, 'store/create_descent.html', context)

def search(request):
    term = ''


    if request.method == 'GET' and 'term' in request.GET:
        # term = form.cleaned_data['term']
        ser = Product.objects.filter(name__icontains=request.GET['term'])
        context = {
            'title': 'Wynik wyszukiwania : ',
            'product_list': ser , 
        }

    return render(request, 'store/search_view.html', context)

store/templates/store/category.html
{% extends "base.html" %}

{% block content %}
<style>
    ul li a {
        text-decoration: none;
        color: chartreuse;
    }
</style>
<ul>
    {% for category in category_list%}
    <li><a href="{% url 'category-details' category.pk  %}">{{ category.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

store/templates/store/create_category.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="DODAJ KATEGORIĘ">
</form>
{% endblock %}

store/templates/store/create_delivery.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

store/templates/store/create_descent.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

store/templates/store/delivery.html
{% extends "base.html" %}

{% block content %}
<style>
    ul li a {
        text-decoration: none;
        color: chartreuse;
    }
</style>
<ul>
    {% for supply in delivery_list%}
    <li><a href="{% url 'supply-details' supply.pk %}">{{ supply.supply_date }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

store/templates/store/descent.html
{% extends "base.html" %}

{% block content %}

{{ descent }}
{% for descent in descent.descent_memory_set.all %}
<p>{{ descent.product }}</p>
<p>{{ descent.quantity }}</p>
<hr>
{% endfor %}

{% endblock %}

store/templates/store/descent_add.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="DODAJ ZEJŚCIE">
</form>
{% endblock %}

store/templates/store/navigation.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <form class="search" role="search" method="GET" action="{% url 'search' %}">
        <input type="hidden" name="name" value="on" />
        <input class="form-search" type="search" placeholder="Search" aria-label="Search" name="term" />
    </form>
</body>

</html>

store/templates/store/products.html
{% extends "base.html" %}

{% block content %}
<style>
    ul li a {
        text-decoration: none;
        color: chartreuse;
    }
</style>
<ul>
    {% for product in products_list%}
    <li><a href="{% url 'products-details' product.pk %}">{{ product.name }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

store/templates/store/products_details.html
{% extends "base.html" %}

{% block content %}

<table>
    <tr>
        <td>TYP : </td>
        <td>{{ product.kind }}</td>
    </tr>
    <tr>
        <td>CENA : </td>
        <td>{{ product.price|floatformat:2 }} zł</td>
    </tr>
    <tr>
        <td>DOSTĘPNA ILOŚĆ :</td>
        <td>{{ product.quantity }} szt.</td>
    </tr>
</table>
{% endblock %}

store/templates/store/search.html
{% extends "base.html" %}

{% block content %}
<form method="GET">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

</form>
{% endblock %}

store/templates/store/search_view.html
{% extends "base.html" %}

{% block content %}
<style>
    ul li a {
        text-decoration: none;
        color: chartreuse;
    }
</style>
<ul>
    {% for product in product_list %}
    <li><a href="{% url 'products-details' pk=product.pk %}">{{ product.name }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

store/templates/store/supply.html
{% extends "base.html" %}

{% block content %}
{{ supply }}
{% for delivery in supply.delivery_memory_set.all %}
<p>{{ delivery.product }}</p>
<p>{{ delivery.quantity }}</p>
<hr>
{% endfor %}
{% endblock %}

store/templates/store/supply_add.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="DODAJ DOSTAWĘ">
</form>
{% endblock %}